<?php
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
/*
?>
<?php
    $theme = $this->helper('fortis');
	$_helper = $this->helper('catalog/product_compare');
	$count = $_helper->getItemCount();
	$_items = $count > 0 ? $_helper->getItemCollection() : null;

   	if ($count > 0)
	{
		$mainTitle = $this->__('Compare Productos');
	}
	else
	{
		$mainTitle = $this->__('No tiene artículos para comparar.');
	}

    //Icon color suffix
    $colorString = $theme->getCfgDesign('header/icon_color');
    $iconSuffix = ($colorString == 'b') ? '' : '-'.$colorString;
?>

<div id="quick-compare" class="dropdown quick-compare<?php echo (!$count ? ' is-empty' : ' is-not-empty'); ?>">

    <div class="dropdown-toggle cover" title="<?php echo $mainTitle; ?>">
    	<div class="feature-icon-hover">
        	<span class="first close-to-text force-no-bg-color icon i-compare<?php echo $iconSuffix; ?>">&nbsp;</span>
	        <div class="name"><?php echo $this->__('Compare'); ?></div>
			<?php if($count > 0): ?>
            	<a class="amount" href="#" title="<?php echo $this->__('Comparar artículos seleccionados') ?>" onclick="popWin('<?php echo $_helper->getListUrl(); ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><?php echo $this->__('(%d)', $count); ?></a>
			<?php else: ?>
            	<div class="amount">(0)</div>
			<?php endif; ?>
            <span class="caret">&nbsp;</span>
        </div>
    </div>
    <div class="dropdown-menu left-hand">
    <?php if($count > 0): ?>
    	<h4 class="block-subtitle"><?php echo $this->__('Elementos(s) agregado(s) recientemente'); ?></h4>
        <ol id="compare-items">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Quitar este artículo') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('¿Estás seguro de que quieres eliminar este elemento de los productos comparar?') ?>');"><?php echo $this->__('Quitar este artículo') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('¿Está seguro de que desea eliminar todos los productos de su comparación?') ?>');"><?php echo $this->__('Clear All') ?></a>
            <button type="button" title="<?php echo $this->__('Compare Productos') ?>" class="button btn-inline" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
    <?php else: ?>
        <div class="empty"><?php echo $this->__('No tiene artículos para comparar.') ?></div>
    <?php endif; ?>
    </div><!-- end: dropdown-menu -->

</div>
<? */ ?>